### ISSUE TITLE
Graceful shutdown in integration tests 

### ISSUE THREAD

**Issue by tyler-mastery** [hienngm/nestjs-graceful-shutdown#10]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**

I was able to get my integration tests working using this solution
```
   ConditionalModule.registerWhen(
      GracefulShutdownModule.forRoot({...}),
      (env: NodeJS.ProcessEnv) => env['NODE_ENV'] != 'test',
    ),
```
But I would prefer to use overrideModule as you [documented in the readme](https://github.com/hienngm/nestjs-graceful-shutdown/pull/9/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R212-R219) but I am having issues creating a mock that doesn't run into this issue

```
Error: You have to invoke `setupGracefulShutdown({ app })` to ensure the proper functioning of `nestjs-graceful-shutdown`.
```

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

I wonder if it's because this is a dynamic module?

**Comment by arjun-traba** [comment]
@tyler-mastery How were you able to get around this? Had a similar Q
