### ISSUE TITLE
Graceful shutdown in integration tests.

### ISSUE THREAD

**Issue by LogansUA** [hienngm/nestjs-graceful-shutdown#4]
- **I'm submitting a question about how to use this project**
- **Summary**

Hey, I'm trying to integrate this module into my existing project. Everything looks alright, except for Integration tests. Currently, all integration tests we have written using the mocha + chai, and the application is created using nestjs testing helpers, like so:
```ts
import { INestApplication } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';

import { AppModule } from '../../src/app.module';

describe('ConfirmTransitionOption', () => {
  let app: INestApplication;

  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
   // <-- `setupGracefulShutdown({ app })` probably supposed to be added here
    await app.init();
  });

  afterEach(async () => {
    await app.close();
  });
});
```

Now when the tests are running, I'm receiving this error
```
Error: You have to invoke `setupGracefulShutdown({ app })` to ensure the proper functioning of `nestjs-graceful-shutdown`.
```
Which I think requires registering the `setupGracefulShutdown({ app })` for each test too. Which is the first thing that I don't want to do for each test 🙂 , but also, when I'm adding it, I'm getting another error in `afterEach` upon `app.close()`
```
Error: Server is not running.
```
I tried to change `beforeEach` and `afterEach` to `before` and `after` cause it seems reasonable to create a server once-per-suite, but the error still happening in `after` for each suite.

So I'm a little bit confused about what I'm facing here.

**Comment by hienngm** [comment]
Hello @LogansUA, thank you for raising the issue. To make this package functional, please ensure that the HTTP server is started. Instead of just calling `.init()`, use `app.listen()`. 
Alternatively, you can override the module with `.overrideModule()`. I'd welcome any improved solutions you might have or, if possible, your contribution through a pull request.
![image](https://github.com/hienngm/nestjs-graceful-shutdown/assets/112270783/aab51802-eac4-4adc-9902-47d0b1e8d260).

**Comment by stepin** [comment]
It's better to cover integration tests in the readme (as I found this ticket only after I solved it).

My approach is to use ConditionalModule:

```ts
    ConditionalModule.registerWhen(
      GracefulShutdownModule.forRoot({...}),
      (env: NodeJS.ProcessEnv) => env['NODE_ENV'] != 'test',
    ),
```

**Comment by hienngm** [comment]
@stepin. Thank you for your suggestion. It has been added. 🚀

**Comment by tyler-mastery** [comment]
@hienngm I was able to get my integration tests working using this solution 
```
   ConditionalModule.registerWhen(
      GracefulShutdownModule.forRoot({...}),
      (env: NodeJS.ProcessEnv) => env['NODE_ENV'] != 'test',
    ),
    ```
I would prefer to use `overrideModule` as you [documented in the readme](https://github.com/hienngm/nestjs-graceful-shutdown/pull/9/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R212-R219) but I am having issues creating a mock that doesn't run into this issue
```
Error: You have to invoke `setupGracefulShutdown({ app })` to ensure the proper functioning of `nestjs-graceful-shutdown`.
```
