### ISSUE TITLE
Propogate the `signal` to the `cleanup` method

### ISSUE THREAD

**Issue by ruscon** [hienngm/nestjs-graceful-shutdown#6]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
here https://github.com/hienngm/nestjs-graceful-shutdown/blob/main/src/lib/graceful-shutdown.service.ts#L55

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by hienngm** [comment]
@ruscon. Thank you for your suggestion 🚀. I've added it in `v1.0.2`
